// Generated by https://quicktype.io

export interface Fighters {
  id:         string;
  name:       string;
  country:    string;
  style:      string;
  img:        string;
  background: string;
}
